# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# directory structure

#github
repository: liximomo/liximomo.github.io

# local
timezone: CN

# Site settings
title: Momo's blog
email: liximomo@gmail.con
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liximomo.github.io" # the base hostname & protocol for your site
imgPath: "/img" # the base hostname & protocol for your site
twitter_username: liximomo 
github_username:  liximomo

exclude:
  - front/

# Posts settings
excerpt_separator: <!--more-->
permalink: /:title

# Conversion
markdown: kramdown
highlighter: rouge

kramdown:
   input: GFM

# defa' front matter
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      css: ["post.css"]
  -
    scope:
      path: "_drafts"
    values:
      layout: "post"
      css: ["post.css"]

# plugin
gems:
  - jemoji
  - jekyll-github-metadata

# sass 
sass:
    style: compressed

#personal info
